[package]
name = "transactinator"
version = "0.1.0"
authors = ["Mark Orel <mail.ormark@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1.1"
clap = "2.33.3"
rust_decimal = "1.8.1"
serde = { version = "1", features = ["derive"] }
itertools = "0.8.2"


[dev-dependencies]
assert_cmd = "1.0.1"
